theaters_by_city = {
    "Armenia": {"cinemark", "cine_col", "royal_films"},
    "Barranquilla": {"cine_col", "royal_films", "cinepolis"},
    "Bogotá": {"cinemark", "cine_col", "royal_films", "cinepolis"},
    "Bucaramanga": {"cinemark", "cine_col", "royal_films"},
    "Buenaventura": {"royal_films"},
    "Buga": {"royal_films"},
    "Cali": {"cinemark", "cine_col", "royal_films", "cinepolis"},
    "Cartagena": {"cine_col", "royal_films"},
    "Cartago": {"royal_films"},
    "Caucasia": {"royal_films"},
    "Cúcuta": {"cinemark", "royal_films"},
    "Dosquebradas": {"royal_films"},
    "Florencia": {"cinemark"},
    "Fusagasugá": {"cine_col"},
    "Girardot": {"royal_films"},
    "Guajira": {"royal_films"},
    "Ibagué": {"cinemark", "cine_col", "royal_films"},
    "Ipiales": {"cinemark"},
    "Itagüí": {"royal_films"},
    "Madrid": {"royal_films"},
    "Manizales": {"cine_col", "cinepolis"},
    "Medellín": {"cinemark", "cine_col", "royal_films"},
    "Montería": {"cinemark", "cine_col", "royal_films"},
    "Mosquera": {"royal_films"},
    "Neiva": {"cinemark", "royal_films"},
    "Palmira": {"cinemark"},
    "Pasto": {"cinemark", "royal_films"},
    "Pereira": {"cinemark", "cine_col", "royal_films"},
    "Popayán": {"cine_col", "royal_films"},
    "Santa Marta": {"cinemark"},
    "Santo Tomás": {"royal_films"},
    "Sincelejo": {"royal_films"},
    "Soledad": {"cinemark"},
    "Tuluá": {"royal_films"},
    "Tunja": {"royal_films"},
    "Valledupar": {"royal_films", "cinepolis"},
    "Villavicencio": {"cinemark", "cine_col", "royal_films"},
    "Yopal": {"cinemark"},
    "Yumbo": {"royal_films"},
    "Chía": {"cinepolis"},
    "Envigado": {"cinepolis"},
}

theaters_url = {
    'cinemark' : ['https://www.cinemark.com.co/cartelera/{city}','https://www.cinemark.com.co/cartelera/{city}/{url_name}'],
    'cine_col' : ['https://www.cinecolombia.com/{city}/cartelera','https://www.cinecolombia.com/{city}/peliculas/{url_name}'],
    'cinepolis' : ['https://cinepolis.com.co/cartelera/{city}-colombia/',''], # -> In Theaters link gives the showtimes
    'royal_films' : ['https://cinemasroyalfilms.com/cartelera/{city}', ''], # -> In Theaters link gives the link to the showtimes
}
